---
title: "Ribeirão Santana"
author: "NEPZAP - UFVJM"
date: "2/18/2020"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE}
require(tidyverse)
require(raster)
require(leaflet)
require(rgdal)
require(rgeos)
require(tmap)
require(sf)
require(sp)
```

## Disponibilidade hídrica

### Ajusta base de dados

```{r importaSentinel}

sentinel_b2 = raster('sentinel_2017_2019_b2.tif')
sentinel_b3 = raster('sentinel_2017_2019_b3.tif')
sentinel_b4 = raster('sentinel_2017_2019_b4.tif')
sentinel_b8 = raster('sentinel_2017_2019_b8.tif')
sentinel_vv = raster('sentinel_2017_2019_vv.tif')
sentinel_vh = raster('sentinel_2017_2019_vh.tif')
srtm = raster('srtm_30m.tif')

```


```{r}
sentinel_b2r = resample(sentinel_b2, srtm)
sentinel_b3r = resample(sentinel_b3, srtm)
sentinel_b4r = resample(sentinel_b4, srtm)
sentinel_b8r = resample(sentinel_b8, srtm)
sentinel_vvr = resample(sentinel_vv, srtm)
sentinel_vhr = resample(sentinel_vh, srtm)

rm(sentinel_b2, sentinel_b3, sentinel_b4, sentinel_b8, sentinel_vh, sentinel_vv)

```


```{r}
stack_bacia = stack(sentinel_b2r, sentinel_b3r, sentinel_b4r, sentinel_b8r, sentinel_vvr, sentinel_vhr, srtm)
rm(sentinel_b2r, sentinel_b3r, sentinel_b4r, sentinel_b8r, sentinel_vhr, sentinel_vvr, srtm)

image.df <- as.data.frame(stack_bacia)  
cluster.image = kmeans(na.omit(image.df), centers=8)

image.df.factor <- rep(NA, length(image.df[,1]))
image.df.factor[!is.na(image.df[,1])] <- cluster.image$cluster

#create raster output
clusters <- raster(stack_bacia)   ## create an empty raster with same extent than "image"  
clusters <- setValues(clusters, image.df.factor) ## fill the empty raster with the class results  

tm_shape(clusters) + 
  tm_raster()
```

```{r}
# filtro de passa baixa
cluster_focal = focal(clusters, w=matrix(1,nrow=11,ncol=11)  , fun=median)
tm_shape(cluster_focal) + 
  tm_raster()

```