---
title: "Delimitação da bacia"
author: "NEPZAP - UFVJM"
date: "2/17/2020"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE}
require(tidyverse)
require(raster)
require(leaflet)
require(rgdal)
require(tmap)
require(sf)
require(maptools)
```

## Delimitação da bacia

### Localiza o rio principal a ser estudado

```{r achaRio}
shp2406 = shapefile("C:/Users/Eric/Documents/GIS DataBase/ZAP_Ribeirao_Santana/2406_JQ_Igam_UFV_reg_vazao_lin.shp")
  proj4string(shp2406) = CRS("+init=epsg:4326")
rioInteresse = shp2406 %>% subset(noriocomp == 'Ribeirão Santana')
rioId = rioInteresse$cocursodag[1]
tm_shape(rioInteresse) + 
        tm_lines("blue") + 
        tm_grid(labels.inside.frame = FALSE, 
                projection = "+proj=longlat", col = 'gray')
```


### Filtra as otto bacias contribuintes

```{r achaOttos}
shp0102 = shapefile("C:/Users/Eric/Documents/GIS DataBase/ZAP_Ribeirao_Santana/0102_jq_otto_bacia_pol.shp")
  proj4string(shp0102) = CRS("+init=epsg:4326")
ottoInteresse = shp0102 %>% subset(grepl(rioId, cocursodag))
#writeOGR(ottoInteresse, ".", "02_ottoBacia_Interesse", driver="ESRI Shapefile")
print(paste(length(ottoInteresse), 'otto bacias encontradas.'))

tm_shape(ottoInteresse) + tm_polygons() +
  tm_shape(rioInteresse) + tm_lines("blue") +
        tm_grid(labels.inside.frame = FALSE, 
                projection = "+proj=longlat", col = 'gray')

```


### Delimita a bacia de estudo

```{r dissolveOttos}
ottoMerged = unionSpatialPolygons(ottoInteresse, IDs = ottoInteresse$nunivotto6)
ottoMerged$area_sqkm <- area(ottoMerged) / 1000000
print(paste(round(ottoMerged$area_sqkm, 4), 'km2 é a área da bacia.'))
#writeOGR(ottoMerged, ".", "01_Bacia_Interesse", driver="ESRI Shapefile")
```


```{r visualizaBacia}
tm_shape(ottoMerged) + tm_polygons() +
  tm_shape(rioInteresse) + tm_lines("blue") +
        tm_grid(labels.inside.frame = FALSE, 
                projection = "+proj=longlat", col = 'gray')
```


### Determina rede hídrica da bacia de estudo

```{r obtemRedeHidrica}

redeHidrica = raster::intersect(shp2406, ottoMerged)
#writeOGR(redeHidrica, ".", "03_RedeHidrica_Bacia", driver="ESRI Shapefile")

tm_shape(ottoMerged) + tm_polygons() +
  tm_shape(redeHidrica) + tm_lines("blue") +
        tm_grid(labels.inside.frame = FALSE, 
                projection = "+proj=longlat", col = 'gray')
```


```{r limpaMemoria}

rm(shp0102, shp2406, rioInteresse, rioId)

```

